provider:
  name: faas
  gateway: http://localhost:8080

functions:

  upload-chain:
    lang: faaschain
    handler: ./upload-chain
    image: s8sg/upload-chain
    environment:
      gateway: "gateway:8080"
      read_timeout: 120
      write_timeout: 120
      write_debug: true
      combine_output: false

  upload-chain-async:
    lang: faaschain
    handler: ./upload-chain-async
    image: s8sg/upload-chain-async
    environment:
      gateway: "gateway:8080"
      read_timeout: 120
      write_timeout: 120
      write_debug: true
      combine_output: false

  colorization:
    lang: Dockerfile
    handler: ./faas-colorization
    image: s8sg/colorization
    environment:
      read_timeout: 60
      write_timeout: 60

  image-resizer:
    lang: dockerfile
    handler: ./cdn_faas/ResizeImage
    image: s8sg/resizer:latest
    environment:
      read_timeout: 60
      write_timeout: 60
