provider:
  name: faas
  gateway: http://localhost:8080

functions:

  upload-chain:
    lang: faaschain
    handler: ./upload-chain
    image: s8sg/upload-chain:latest
    environment:
      gateway: "gateway:8080"
      chain_name: "upload-chain"
      read_timeout: 120
      write_timeout: 120
      write_debug: true
      combine_output: false
      enable_tracing: false
      trace_server: "jaegertracing:5775"


  upload-chain-async:
    lang: faaschain
    handler: ./upload-chain-async
    image: s8sg/upload-chain-async:latest
    environment:
      gateway: "gateway:8080"
      chain_name: "upload-chain-async"
      read_timeout: 120
      write_timeout: 120
      write_debug: true
      combine_output: false
      enable_tracing: false
      trace_server: "jaegertracing:5775"

  colorization:
    lang: dockerfile
    handler: ./faas-colorization
    image: s8sg/colorization:latest
    environment:
      read_timeout: 60
      write_timeout: 60

  image-resizer:
    lang: dockerfile
    handler: ./cdn_faas/ResizeImage
    image: s8sg/resizer:latest
    environment:
      read_timeout: 60
      write_timeout: 60

  facedetect:
    lang: go-opencv
    handler: ./facedetect-openfaas/facedetect
    image: s8sg/facedetect:latest
    environment:
      input_mode: "image"
      output_mode: "image"

  file-storage:
    lang: dockerfile
    handler: ./cdn_faas/file_storage
    image: s8sg/file-storage:latest
    environment:
      read_timeout: 60
      write_timeout: 60
