provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  faaschain:
    lang: go
    handler: ./faaschain
    image: faaschain
    environment:
            # The default method that will be used to call function 
            # if not specified by param
            default-method: "POST" # if not specified it will use POST
            gateway-url: "http://gateway:8080/"
            read_timeout: 300s
            write_timeout: 300s
