provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  faaschain:
    lang: go
    handler: ./faaschain
    image: faaschain
    environment:
            # The default method that will be ued to call function 
            # if not specified by param
            default-method: "POST" # if not specified it will use POST
