provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  titleize:
    lang: go
    handler: ./titleize
    image: titleize
  format:
    lang: go
    handler: ./format
    image: format
  makeuserid:
    lang: faasflow
    handler: ./makeuserid
    image: makeuserid
    environment:
       workflow_name: "makeuserid"
       gateway: "gateway:8080"
       enable_tracing: false
       enable_hmac: false
       write_debug: true
       combine_output: false
